### ISSUE TITLE
SampleOffer.sol -> sign() method -> Sanity check parameters should be an OR instead of an AND.

### ISSUE THREAD

**Issue by jbaylina** [slockit/DAO#124]
I believe that in SampleOffer.sol, in the sign() method (line 81) the signature should not be accepted if total cost is not transfered OR is already signed.

In the code there is an AND ( && ) instead of an OR ( || ). If I understand the contract, this is a bug and this should be an OR ( || ).

**Comment by LefterisJP** [comment]
Yes I think you are right. We have not update the SampleOffer.sol in a while, we are starting to look at it right now. Thanks for noticing!
