### ISSUE TITLE
Contractors should be able to terminate contract with DAO in sample contract

### ISSUE THREAD

**Issue by aquabu** [slockit/DAO#143]
Termination clauses for contractors are frequently symmetrical and may require x days of warning. Sometimes they are terminate at will.

Seems like contractors should have a function similar to returnRemainingMoney() that indicates that they are terminating the relationship with the DAO. This might be necessary in cases like a crash in the value of Ether leading to an inability of the contractor to adequately compensate workers for an extended period of time:
https://github.com/slockit/DAO/blob/master/SampleOffer.sol#L92

**Comment by CJentzsch** [comment]
That is just a SampleOffer. If the contractor can terminate the contract, he could run with the initial payment without delivering anything.
Such features can be implemented by each contractor by there individual contract.
