### ISSUE TITLE
Feature request: User land liquid democracy

### ISSUE THREAD

**Issue by colm** [slockit/DAO#144]
Me and @Hiro_Mant had a chat in #art_of_the_DAO about implementing liquid democracy in "user land" with a separate contract that acts as intermediary. 

Basically a DTH send there tokens to this contract and defines a second delegate DTH. The contract then "watches" the DAO and votes the same way the delegate votes. If the delegate choses to split the contract splits but withdraws the original users ETH to their account. This provides the same level of security as the original contract. White reducing the need for active voters. 

This would require making a contract `delegate.sol` with this functionality. A user would then deploy this and set it up to delegate their vote. 

I think this is an elegant way to implement complex features like liquid democracy with minimum changes to the base `DAO.sol` contract.

**Comment by CJentzsch** [comment]
Done right, it could even be done without changing DAO.sol, and work with the current version.

**Comment by colm** [comment]
@jbaylina has a (prototype)[https://github.com/jbaylina/DAO/blob/dthPool/dthpool.sol]

**Comment by jbaylina** [comment]
Created a pull request for this: 
https://github.com/slockit/DAO/pull/153

**Comment by CJentzsch** [comment]
implemented with #154
