### ISSUE TITLE
Disallow sending money from the DAO to the `extraBalance`

### ISSUE THREAD

**Issue by LefterisJP** [slockit/DAO#149]
As it currently stands, a proposal to send money to the extra balance would work. This should not be allowed.

**Comment by colm** [comment]
https://github.com/slockit/DAO/blob/master/DAO.sol#L577

`&& p.recipient != address(extraBalance)`

**Comment by LefterisJP** [comment]
Closing the issue in favour of: https://github.com/slockit/DAO/issues/163
