### ISSUE TITLE
DIR 1 - Remove extrabalance

### ISSUE THREAD

**Issue by LefterisJP** [slockit/DAO#163]
### Changelog
- 23 - 05 - 2016 Issue created
- 13 - 06 - 2016 Turned the issue into a [DAO Improvement Request](https://github.com/slockit/DAO/wiki/DAO-Improvement-Requests)
### Problem Description

For the original DAO deployment the notion of an `extraBalance` account was used in order to keep the extra funds sent to the DAO by potential DAO Token Holders after the lowest price DAO creation phase was over.

This was due to initial requests by the community to provide for variable price on the DAO tokens during the creation period. The existence of the `extraBalance` and the fact that the DAO needs to spend as much as is in the `extraBalance` to be able to access it creates a lot of complications both during the creation phase of the DAO and after.
### Proposed Solution.

Completely Remove the `extraBalance` from the code. Here is the PR that provides the implementation for this: https://github.com/slockit/DAO/pull/244

**Comment by pdulong** [comment]
What will happen to the balance in the extraBalance account?

**Comment by LefterisJP** [comment]
@pdulong It will be moved to the DAO's balance.

The DAO will make a proposal to move the balance of the `extraBalance` account back into the actual DAO balance so that it can use it.

The new contract won't need any extra balance.

**Comment by cougarously** [comment]
This is labeled as a feature but it I just wanted to point out that DAO.minQuorum(_amount) is currently not being calculated properly because of this.

This is because minQuorum() is a function of the DAO.actualBalance() which does not take into consideration the extraBalance. actualBalance() is a function of the DAO's this.balance so once this extraBalance is moved over the minQuorum() will fix itself.

So in actuality, anywhere actualBalance() is used is currently not 100% accurate.

**Comment by LefterisJP** [comment]
@cougarously The minQuorum was not supposed to count the balance of the extra balance so there is nothing wrong here.

**Comment by cougarously** [comment]
@LefterisJP  - ok but once extraBalance is removed and the funds in that ManagedAccount is moved to the DAO.balance, minQuorum will start counting it, correct?

**Comment by LefterisJP** [comment]
In that case yes.

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228

**Comment by pdulong** [comment]
If the extraBalance is moved to the mainBalance, will users be able to withdraw their extraBalance paid or is the exchange ratio, in case of a split, still fixed?

**Comment by LefterisJP** [comment]
@pdulong no they won't. This was never the intention.

**Comment by LefterisJP** [comment]
This issue is no formatted as a [DIR](https://github.com/slockit/DAO/wiki/DAO-Improvement-Requests) and is at the draft stage.

**Comment by CJentzsch** [comment]
done
