### ISSUE TITLE
Splitting after the proposal debate period

### ISSUE THREAD

**Issue by LefterisJP** [slockit/DAO#164]
Splitting was conceived and implemented as a last resort to leave the DAO in the case of a malicious curator, but it seems that people also start seeing it as a way to disagree with a proposal. Some people may want to leave in the case a proposal goes through.

With [DAO v1.0](https://github.com/slockit/DAO/releases/tag/v1.0) there would be a race condition, since right after the proposal debate period ends, the proposal can be immediately executed. So there is not enough time to split before people know the outcome of the vote. 

Although it is likely that the result will be obvious before the last second of the debate period, technically it is also possible for all votes to happen in the last block before the period ends, introducing an uncertainty to potential splitters.

This uncertainty can be easily fixed by setting a Grace Period between the end of the proposal debate period and the execution of the proposal so that people who really want to split because of the result of a vote can wait until the end of this vote to do so.

**Comment by D-Nice** [comment]
https://github.com/D-Nice/DAO/commit/12ff5b45571969d0e7bf93bc646d975636704074

This should take care of the race condition, allowing for a grace period that can be set in the contract, I've set it to 10 days.

**Comment by D-Nice** [comment]
I opened this PR that was tested on Morden, it would stop a proposal from being executed, until the split grace period passes, allowing a timeframe for a split to be proposed and successfully done before a proposal is executable.

https://github.com/slockit/DAO/pull/188

**Comment by colorics** [comment]
Help me ! I did - Proposal_ID: 9 (DAO split proposed)
TimeStamp: 8 hrs 9 mins ago (2016-05-29 12:59:52 +00:00)
Created By: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
Recipient: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
 This purse -https://etherscan.io/address/0xc0f5228127fe170c6c26e46a1462a86403fd726c - vote - YES!
He wants to steal my - ETH -? What should I do???

**Comment by colorics** [comment]
Help me ! I did - Proposal_ID: 9 (DAO split proposed)
TimeStamp: 8 hrs 9 mins ago (2016-05-29 12:59:52 +00:00)
Created By: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
Recipient: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
This purse -https://etherscan.io/address/0xc0f5228127fe170c6c26e46a1462a86403fd726c - vote - YES!
He wants to steal my - ETH -? What should I do???

**Comment by D-Nice** [comment]
Don't split. Wait until the solo split function is implemented.

**Comment by nepaldude** [comment]
Some people are splitting by doing arbitration. For example right now some tokens are selling below creation prices and there are some who are buying this up and splitting it.

**Comment by D-Nice** [comment]
You mean arbitrage. They may be in for a surprise, when they try splitting, and are unable to withdraw funds from the split DAO due to stalker attack. Until solo splitting is implemented, there is no arbitrage.

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228
