### ISSUE TITLE
Nay voters help proposals reach quorum

### ISSUE THREAD

**Issue by LefterisJP** [slockit/DAO#165]
Since the quorum takes both `yea` and `nay` votes into account, there may be cases where the quorum is just barely reached, and would not have been reached without the `nay`-voters.

Because of this people who want to vote against a proposal are disincentivized to do so. This can be easily fixed by only counting the `yea` votes of a proposal towards its quorum.

**Comment by jeffanthony** [comment]
It seems this would introduce an incentive to vote 'Yes' early and 'No' later. Perhaps that dynamic could be strengthened by allowing the extant debatePeriod to be a preliminary vote to determine weather Quorum  is met and, if so, then allot an extended period (2-3 days) to allow for 'No's and splits to trickle in and finalize the ballot count.

**Comment by nepaldude** [comment]
Voting like anything else is an altrustic act done by a citizen of that society. We have created a DAO
 society. Voting means taking responsibility. Responsible members in a society need to have a chance to do better than the lazy/unproductive members of the society. It's a pure libertarian ideal. I think we need to taking voting into account with slightly different approach. I like mechanisms proposed through Gnosis and that should be our long term goal. We should also integrate karma points. I outline mechanisms to do so on this paper. Please give it a good read and consider some of my proposals for improving DAO citizenship. 

[DAO GOVERNANACE AND VOTING PROPOSAL.pdf](https://github.com/slockit/DAO/files/289801/DAO.GOVERNANACE.AND.VOTING.PROPOSAL.pdf)

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228
