### ISSUE TITLE
Curator can remove DAO from allowed recipients

### ISSUE THREAD

**Issue by pirapira** [slockit/DAO#190]
The curator can call `changeAllowedRecipients(address_of_dao, false)`.  After that the DAO cannot receive rewards because it cannot call `retrieveDAOReward()`.  The Token holders will need to split before receiving rewards.

**Comment by CJentzsch** [comment]
Malicious curator, means you have to split anyway.

**Comment by pirapira** [comment]
That's very true.  No hurries then.

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228
