### ISSUE TITLE
mandatory voting

### ISSUE THREAD

**Issue by jpritikin** [slockit/DAO#191]
We can expect better decisions if more people vote. Mandatory voting is one way to ensure that voting happens. Australia and some S. American countries do it. Either vote or forfeit 1 DAO token or some small percentage of your DAO tokens.

One way to address vacations and voter fatigue is to allow DAO holders to nominate some other holder to vote for them ("liquid democracy"). There is already an issue and pull request for something similar.

**Comment by D-Nice** [comment]
I disagree that we can expect better decisions this way. Abstention is as much a part of democracy as a yea or nay vote. Being forced to choose one isn't.

**Comment by jpritikin** [comment]
The premise of democracy is that we make better decisions when everybody weighs in. If you decide not to participate then you are depriving the rest of us of your valuable opinion. Once we have delegative democracy (a.k.a. liquid democracy) then how much burden is it to vote? I think it is not much of a burden at all. Maybe we'll get 70-80% participation without any punishment for not voting. However, I still like the idea of mandatory voting with a punishment. It makes clear that the point of democracy is participation.

**Comment by D-Nice** [comment]
But if I don't have any wisdom on a subject at hand, and I am forced to choose either yea or nay, I think that's more of a detriment to the democratic process, rather than allowing those who do have wisdom and strong opinions on the subject to make a decision for me.

**Comment by jpritikin** [comment]
> But if I don't have any wisdom on a subject at hand, and I am forced to choose either yea or nay

Being force to vote is an incentive for you to develop your expertise on the subject at hand. Democracy rests on education. If you reject education then you are not contributing to the democratic decision making---you are deadweight---and I am happy for you to sell your tokens to someone else. Look, I'm not asking for a lot. With liquid democracy, all you have to do is find a token holder who you judge is more expert than you. That should be easy if you believe that you don't know anything, but even that choice is at least a small contribution to collective decision making.

**Comment by D-Nice** [comment]
Then the solution is liquid democracy, not mandatory voting. I don't think it's something many people in the DAO agree with, and if this had been a rule, the DAO likely wouldn't have made it past 10 million. You assume people have the time and willingness to learn new things, when kids are in school they barely have the willingness to learn, in majority of cases, if you're expecting someone to go out and learn every subject that they are ever met with, to be part of a democratic process, then that is beyond idealism. 

As mentioned, I believe we should be given more choices, not narrowed down between choosing either yes or no. Abstention sucks, but it's the best alternative we currently have. Of course, adding liquid democracy would be optimal.

Now to close, I wanna make it very clear, I wish we all could just vote yea or nay, in an ideal environment it would be great. The world, however, is less than ideal.

**Comment by D-Nice** [comment]
Another things I must say is that mandatory voting, would actually open up another attack vector. We would need to be able to filter out valid proposals, otherwise, someone could just start spamming proposals, and force thousands of DTH waste their ether on gas for votes.

**Comment by CJentzsch** [comment]
I prefer liquid democracy over that.
