### ISSUE TITLE
Viability of merging DAOs

### ISSUE THREAD

**Issue by D-Nice** [slockit/DAO#193]
As of now, I don't see the possibility of merging existing DAOs, although if I'm wrong, please correct me. The only possibility I see, is if people split from their existing DAOs, get a refund, and then reinvest in a whole new DAO, they are able to pseudo-merge.

However, what would be the viability of implementing a merge function, is it possible to keep most of the current code intact or would this require a rewrite? The merge should only be possible between 2 identical DAO contracts.

**Comment by LefterisJP** [comment]
It's quite an intriguing thought @D-Nice! 

We never designed the DAO in the beginning to ever be re-mergeable after a split. I believe that this would require a considerable rewrite.

What would be the benefits of a merging mechanism apart from the ability to rejoin a DAO you split from when the reason you split is no longer a threat to you?

**Comment by D-Nice** [comment]
A more attractive DAO. Larger DAOs will be the ones to attract more proposals, I would presume. Several child-DAOs might want to merge together, to compete against their parent-DAO. People that may have missed an earlier split, may want to be part of that split, and the only possibility would be with a DAO merge. 

Or even, if the parent-DAO a child-DAO split from, gets its act together again, the child-DAO may wish to merge with it for future proposals.

I will try and inspect the code more, I was hoping this would be a possibility without a major rewrite, since the current code in place is quite good, but I think that's still major thinking for such a complex function. There would need to be a way of properly assigning or reassigning rewardTokens and some agreement on DAOs that may not be from the same parentDAO on their token value and redistribution of tokens in the merged DAO.

**Comment by D-Nice** [comment]
Another possibility would be to create a buy-in or merge smart contract, that would need to be passed as a proposal first. In the case of a buy-in, it would allow anyone with ETH to get into the DAO, or in case of a merge smart contract, it would only allow a pre-defined list of accounts, usually from the DAO looking to merge, to buy in with their ETH or simply restrict it to the DAO that wishes to merge itself. 

In this case, a portion of tokens from all DTH would need to be transferred to said buy-in/merge smart contract, and then that smart contract would divide the tokens up based on the buy-ins.
