### ISSUE TITLE
The current split mechanism prevents grandchild (and further descendant) DAOs from collecting rewards.

### ISSUE THREAD

**Issue by isaidgitout** [slockit/DAO#194]
Consider the scenario:
1. `DAO A` spends money on a proposal
2. `DAO B` splits from `DAO A`. This means that `DAO B` is added to `DAO A`'s `rewardToken` mapping. When ETH is transferred to the `DAOrewardaccount`, `DAO B` can collect their share.
3. `DAO C` splits from `DAO B`. This change is not reflected in `DAO A`'s `rewardToken` mapping. `DAO B`'s `rewardToken` mapping is updated to assign rewards to `DAO C` **in proportion to the amount of ETH they spent from `DAO B`**. In the extreme case, if the token holders of `DAO C` never spent any money in `DAO B`, they are not represented in `DAO B`'s `rewardToken` mapping. `DAO C` will correctly receive their share of rewards at the time of the split, but any future rewards that they are entitled to from `DAO A` are now lost forever (or more accurately - their rewards are (incorrectly) distributed among the `DAO B` token holders)

The solution is for the DAO to record the number of tokens it has distributed to child DAOs. In this way, the relevant proportion of tokens belonging to `DAO B` and `DAO C` are publicly queryable from any contract. `DAO A` can then include a mechanism (that anyone can call) to add `DAO C` to its `rewardToken` mapping, while reducing the rewards owed to `DAO B` appropriately. This solution has the added advantage that descendant DAOs can claim their rewards directly from the DAO that earned them, without having to go through the intermediate DAOs.

**Comment by LefterisJP** [comment]
Yes we are aware of this, the splitting mechanism was designed like this so that a grandchild DAO does not get any rewards from the grandparent.

It is also a way to disinsentivise people from multiple splitting.

**Comment by D-Nice** [comment]
In that case we definitely need solo splitting.

**Comment by colorics** [comment]
Help me ! I did - Proposal_ID: 9 (DAO split proposed)
TimeStamp: 8 hrs 9 mins ago (2016-05-29 12:59:52 +00:00)
Created By: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
Recipient: 0x228d29ea776cb17ca0db0538562ecaacdc0a9e46
This purse -https://etherscan.io/address/0xc0f5228127fe170c6c26e46a1462a86403fd726c - vote - YES!
He wants to steal my - ETH -? What should I do???

**Comment by isaidgitout** [comment]
Hey colorics, this is probably not the best place to ask the question. Check out the slack: https://thedao.slack.com. There are lots of people there answering questions all day long.

But as a quick answer: 
1. Firstly, if they are engaged in a _stalking attack_, all that means is that they follow you to your new DAO and prevent you from withdrawing your funds. It's annoying, but they can't actually take your funds. In the mean time, they're locking up at least as much money as you are (they can't withdraw their funds either until they give up on the attack). The only way this helps the attacker is if they're willing to wait longer than you are, and you're willing to pay them to leave. Be patient and eventually they'll leave. 
2. More importantly for your case: your split proposal is not binding. When the debate period expires, you have the option of calling `splitDAO`. If you choose not to call it, you will remain in the main DAO. Soon the main DAO will have the option of moving to a new contract with solo splitting (which prevents the _stalking attack_). I'm not sure what happens if the DAO doesn't vote to move, but you'd be in the same boat as everyone else, so there would be lots of people trying to figure out a solution.

**Comment by jbaylina** [comment]
Last week I wrote a PR to solve this:

https://github.com/slockit/DAO/pull/162

**Comment by D-Nice** [comment]
Can this be added as a feature milestone? I think V1.1 is mostly concentrated on outstanding security issues, so would this be in a 1.2 milestone?
