### ISSUE TITLE
DAO Tokens must be moved after call to newContract()

### ISSUE THREAD

**Issue by dirtyfilthy** [slockit/DAO#199]
As it stands, after a call to newContract(), the old DAO tokens must be traded in for new contract tokens. This involves exchanges having to change the address of the token contract, a potential time lag for people moving to the  new system (perhaps missing out on reward tokens), and general headache. 

This will be unavoidable for the first upgrade, however one solution could be moving the tokens to a separate sub-contract. This contract could have special owner only-functions for burning or blocking tokens. Ownership of this sub-contract could then be passed from contract to contract as part of a call to  newContract.

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228
Still, every token holder need to call a function there called `swapToken`. 
Since one can not loop over all the addresses, there is no way to avoid this.
