### ISSUE TITLE
Issues testing out new MIST update

### ISSUE THREAD

**Issue by jtaylor1173** [slockit/DAO#201]
After updating the Ethereum Wallet to Mist Mode.  I am having issues when attempting to test out the voting.  Everything works fine all the way up to the time to vote.  It brings up the options.  I select a vote, but after that when it is supposed to prompt me for my password.  It does nothing. 

Any suggestions on what I have done wrong?

**Comment by LefterisJP** [comment]
This is a Mist issue not a DAO contract issue. Unfortunately mist browser (the one you are trying to use) is still not really ready and there has been no official working release. 

For more info and support on mist you can:
1) Make an issue on their [repository](https://github.com/ethereum/mist)
2) Join their conversation and support channel in [gitter](https://gitter.im/ethereum/mist)
