### ISSUE TITLE
It is difficult to discover what code will be executed if a proposal has passed

### ISSUE THREAD

**Issue by dirtyfilthy** [slockit/DAO#203]
Currently on proposal creation, a proposalHash is created via sha3(_recipient, _amount, _transactionData) to enforce that the right code is called during a call to executeProposal(). While this might save space, it also makes it difficult when browsing proposals to see what _transactionData consisted of without examining the original transaction that created the proposal. 

_transactionData should be added as a field to the Proposal struct, or at the very least, the data should be propagated by the ProposalAdded() event, so that various automated tools in use by the community can make it available (dao.report et al)

**Comment by CJentzsch** [comment]
solved in https://github.com/slockit/DAO/pull/228
