### ISSUE TITLE
There is no way to get historical proposal votes

### ISSUE THREAD

**Issue by pipaman** [slockit/DAO#204]
I'm trying to get the historical votes of the proposals in the same way:
https://etherscan.io/token/TheDAO#votes

But there isn't a way. I tried handling events in Geth console:
```
> var theDAOVotedEvent = theDAO.Voted({fromBlock: 1600769, toBlock:1618798});

> theDAOVotedEvent.watch(function(error, result){
  console.log(JSON.stringify(result));
});

```
But it only reports the new votes but I can't get the old ones. I read the code and it makes sense since the only place Voted event is called is in vote function.
I also tried to replace .watch with .get just in case, but I don't get any vote with this change.

Is there any way to access _Proposal.votedYes_ and _proposal.votedNo_ or any other way to get the same 
information?

Thanks on advanced,
Pablo Yabo

**Comment by psionic81** [comment]
you can use the events with a new full node to output over time to a database. it will perform every transaction on the ethereum network since the beginning.

**Comment by pipaman** [comment]
Thank you for the suggestion. I did it and it worked perfect.
