### ISSUE TITLE
Paying for gas price from another ethereum address

### ISSUE THREAD

**Issue by psionic81** [slockit/DAO#212]
Use case:

user has ether balance in address A
user has dao tokens in address B (transfer) C (transfer/voting) D (voting)

it would be super if the contract be passed a message signed by B, C, D to transfer dao tokens from the address, and use A's ether balance to pay for the mining fee.

**Comment by LefterisJP** [comment]
That has nothing to do with the DAO contract itself. Gas is paid by users who initiate transactions, not contracts.

> it would be super if the contract be passed a message signed by B, C, D to transfer dao tokens from the address, and use A's ether balance to pay for the mining fee.

I really don't see the use for this, not to mention the complexity such a thing would add is enormous for arguably almost zero benefit.

There should be a clear separation to what the Operating System (The DAO contract) should be reponsible for and what the user land applications (users, dapps, other contracts reading from The DAO) should do.

**Comment by GriffGreen** [comment]
Can the Approve function help here at all? I think that if B C and D all Approve A then A can pay the gas for transfers.... but Voting requires Eth in the account that is voting... there is just no way around that.

**Comment by psionic81** [comment]
re: approve, it would still need to be called from the account with the dao tokens, which would require gas.

it's the "onlyTokenholders" modifier that limits the voting, I'm thinking a method where the data passed into the function could contain a signed "okay" from the B address, which is processed through another vote type function.

the gist of the use case is easy.. our wallet can "send max", which will drain all of the accounts of ether. if I could pick an address and use that to pay the gas for a signed transfer from a dao-holding account, I wouldn't have a really weird use case of "oh sure, but before you vote/transfer your tokens, we need to charge N * fee to transfer ether into all these dao accounts. and then you have to wait. with your app in the foreground. and then pay N * fee again in order to actually do the transfer/vote."
