### ISSUE TITLE
Clean up Token.approved mapping

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#215]
Token.approve(...,uint256 _amount) and Token.approveAndCall(..., uint256 _amount, ...) should both check that _amount > 0 to keep the allowed[][] mapping clean and to avoid the possibility of introducing any overflow issues in the future.

**Comment by LefterisJP** [comment]
Hmm ... yes I do see your point here. That would be a nice check to have.

@cougarously: One note for formatting: You should put code inside \`   \` so that it's nicely formatted in markdown

@CJentzsch: What do you think aout adding this?

**Comment by CJentzsch** [comment]
No, because setting it to 0 is also a way to remove the approval.
And with 2**256 bits there will be no overflow issues.
