### ISSUE TITLE
Simplify the DAO

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#216]
I suspect that it maybe, understandably, too late for this suggestion for The DAO but maybe something for another future DAO.

I'm new to Solidity and the DAO but as I have reviewed all of the DAO code over the weekend and while there is not that much code it's pretty easy to do something incorrect and the more complex, the more chances of missing something critical that may put much at risk.

Again, it's probably too late for this for THE DAO and if it were suggested to the wider token holder audience it would probably produce outrage (Disclosure: I am a DAO token HODLER) but I'm going to ask anyway: Can we not allow splits at all? This would simplify SO much. Current corporations don't allow the equivalent of a DAO split. A corporation obtains cash from various source of funding and returns from their projects. As a shareholder of a corporation you cannot simply ask/propose for your portion of cash and for your portion of the upside for past funded projects. If you want cash, you sell your shares and you are done - simple.  One other way shareholders get cash is if there is a dividend distribution but it is distributed out to all shareholders equally.

This would simplify the DAO tremendously, making it more maintainable and safer too (no stalker attack, etc). It would allow for the removal of all the split logic and the baggage that goes with it like maintaining state like reward tokens, splitData, etc. If token holders want/need ETH, they can sell their tokens on an exchange or propose a dividends proposal where a % of DAO funds would be distributed  to all token holders equally - this would require small amount of code but would be much simpler, something line this:

my dividend = (dividend % * (DAO.balance + extraBalance - sumOfProposalDeposits)) * (balance[me] / totalSupply)

Just a thought...

**Comment by LefterisJP** [comment]
Removing splits totally would be kind of hard and not really advised.

 But in the next version of the DAO we want to also add a function that would add the ability to simply quit the DAO and get your money out. Essentially a guaranteed solo split to avoid even the possibility of stalker attack.

If you read the [white paper](https://download.slock.it/public/DAO/WhitePaper.pdf) splits are there as a method to protect the DTH against a malicious curator. If the curator starts doing bad things then all the DTH can decide to group together and split to another DAO, leaving the curators with an empty DAO and escaping from their control while still keeping the ability to withdraw rewards from whatever they funded in the original DAO.

As for general simplification of the DAO ... I am with you ... we always wanted to keep it simple. The contract at the beginning was a lot more simple, but as attack vectors were discovered during testing and auditing complexity was added to defend against them.

I am going to close this issue as it's more of the nature of a discussion and github issues are not for this. You are welcome to join the [DAO Slack chat](http://thedao.signup.team/) and join one of the many channels were the code is discussed and also improvements for the next version of the DAO are debated!

**Comment by cougarously** [comment]
That makes sense thanks @LefterisJP!
