### ISSUE TITLE
DAO.vote() doesn't return anything

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#218]
The vote function does not return (_voteID) even though it says it supposed to.

I'm new to Solidity so maybe there is a default return from every function even if it's not explicitly made in the function but I couldn't find it anywhere in the docs. 

```
function vote(
    uint _proposalID,
    bool _supportsProposal
) onlyTokenholders noEther returns (uint _voteID)
{
   [... _voteID not assigned nor do we return anything from here ...]
}
```

**Comment by LefterisJP** [comment]
No that is indeed missing. We just never really used it anywhere and as such nobody considered it as a bug since there is really no use for the voteID if returned from here.

Still it should either be added or the function should return nothing.

**Comment by cougarously** [comment]
Just for my education, if we assigned _voteID to something within the vote function, but never explicitly call return _voteId, does it implicitly return the proper value?

**Comment by LefterisJP** [comment]
@cougarously yes exactly, there are two ways to return things in solidity as you can check in the docs [here](https://solidity.readthedocs.io/en/latest/control-structures.html?highlight=return#expressions-and-control-structures)
