### ISSUE TITLE
Can a split DAO get more funds than it should?

### ISSUE THREAD

**Issue by cougarously** [slockit/DAO#225]
In DAO.splitDAO() we make a call to send value like follows:

```
if (p.splitData[0].newDAO.createTokenProxy.value(fundsToBeMoved)(msg.sender) == false)
   throw;
```

If DAO.splitDAO() is called repeated in a malicious manner, there is nothing validating not to run the above code again.

Should we move where we currently set `p.proposalPassed = true` from it's current location:

```
// If the new DAO doesn't exist yet, create the new DAO and store the
// current split data
if (address(p.splitData[0].newDAO) == 0) {
   ...
   ====> Should we set p.proposalPassed before the above 'if' statement? <====
   p.proposalPassed = true;
   ...
}
```

And then also make a check for it at the top of the splitDAO():

```
if ( ====> p.proposalPassed || <===============
    now < p.votingDeadline  // has the voting deadline arrived?
    //The request for a split expires XX days after the voting deadline
    || now > p.votingDeadline + splitExecutionPeriod
    // Does the new Curator address match?
    || p.recipient != _newCurator
    // Is it a new curator proposal?
    || !p.newCurator
    // Have you voted for this split?
    || !p.votedYes[msg.sender]
    // Did you already vote on another proposal?
    || (blocked[msg.sender] != _proposalID && blocked[msg.sender] != 0) )  {

    throw;
}

```

**Comment by LefterisJP** [comment]
Hey again @cougarously !

No there is no need for any of this. If you look at 
`if (p.splitData[0].newDAO.createTokenProxy.value(fundsToBeMoved)(msg.sender) == false)`
you will notice that it moves `fundsToBeMoved`.

This is calculated as `(balances[msg.sender] * p.splitData[0].splitBalance) /p.splitData[0].totalSupply;`

After a succesfull call to `splitDAO()` the balance of `msg.sender` become zero, so nothing is transferred.

Does this answer your question?

**Comment by cougarously** [comment]
Ah yes, I just realized that if we did what I suggested it would not allow multiple senders to join a new split DAO since it would only allow the `splitDOA()` to be effectively called once.
