### ISSUE TITLE
DIR 7 - Remove quorum and add an external "Proposal Acceptance Contract"

### ISSUE THREAD

**Issue by jbaylina** [slockit/DAO#254]
### Changelog
- 2016-06-14  Issue created
### Problem description

The quorum mechanism in DAO 1.0 carries perverse voting strategies that brings to the "Yes Bias" and the "Ambush attack".  
### Problem solution

The solution that I propose is that only a special  "Proposal Acceptance Contract" is allowed to submit proposals to the DAO. 
This contract will hold the rules required to accept the proposals. 
In his first version this rules can be:
- The proposal must be whitelisted by the curators
- A 10% of DTHs supports this proposal.
- Curators can always submit a proposal

This contract can be changed by a regular proposal.

In future versions of this contracts, new rules can be added like for example:
- Limit the number of proposals per week
- Limit the amount of Ether that a proposal can ask.

This proposal also allows to remove the "Recipient Whitelisting" mechanism of the current DAO 1.0.

**Comment by GriffGreen** [comment]
@jbaylina Would the DAO need to upgrade to change the "Proposal Acceptance Contract" or could that be done in a more modular manner?

**Comment by JasonMcz** [comment]
> In future versions of this contracts, new rules can be added like for example:
> Limit the number of proposals per week

I like the idea of limiting number of proposals per week, but who determines the queue? What proposal will be in the pipeline verses currently being voted by the DTH community.

> Limit the amount of Ether that a proposal can ask.

This is redundant feature in my opinion because people who are voting get to decide themselves, if they think valuation or the ask cannot be properly justified by the proposal -- they simply just don't vote yes on it. What do you think?

**Comment by jbaylina** [comment]
@GriffGreen: No, The DAO Contract does not be needed to be upgraded in order to change this contract. 
The normal way to change  the "Proposal Acceptance Contract" is via a regular proposal. 

It could be good that in the firsts versions of the DAO, curators can submit a proposal directly to the DAO bypassing the "Proposal Acceptance Contract" .

**Comment by jbaylina** [comment]
@JasonMcz: The intention of this DIR is not to define the rules of the "Proposal Acceptance Contract". The proposal just talk about a first version of this contract that just asks for a percentage of DTH tokens in order to submit the proposal to The DAO and the acceptance of curators in order that they can review the code. 

The limits that I talk in the second part of the DIR, are just examples of what could be done in future contracts if DTH agree to change this contract. 

Maybe it would be good to submit a DIR with a set of rules of how this "Proposal Acceptance Contract" should implement.
