### ISSUE TITLE
DIR 8 - Accounts should never get blocked because voting

### ISSUE THREAD

**Issue by jbaylina** [slockit/DAO#255]
### Changelog

2016-06-14: Dir created
### Problem Definition

When a DTH vote, his account gets blocked and he cannot transfer his tokens to anyone. He also can not receive tokens to this blocked account ether.

This characteristic of the DAO 1.0 disincentives voting because limits the trading option of those tokens.

There is also an incentive to vote at the end of the debating period. This can carry a saturation of the Ethereum network at the end of the voting period. This can bring to a situation where some DTHs can not vote. 

This can also get worst if some attacker tries to saturate the network during the last minutes of the voting period.
### Proposed solution.

The idea is that when a proposal is submitted and a voting starts, a "snapshot" of the current Token distribution is done. Then all the voting rules is based in this "census snapshot"

To do this snapshot with minimal gas, the following algorithm is proposed:

```
struct  VotesAssignedToTokenHolder {
    // proposal when starts to take effect this assignation
    uint fromProposalId;
    // nomber of votes assigned to token holder from proposal
    uint votes;
}
mapping (address => VotesAssignedToTokenHolder[]) votesAssignedToTokenHolders;
```

This data structure defines an array of  `VotesAssignedToTokenHolder`struct for each DTH.

This struct is interpreted this way: 

This DTH has `votes` tokens for voting in all the proposals starting at proposal `fromProposalId` and util `fromProposalId` of the next element of the array -1.

If this is the last element of the array, that is exactly the number of tokens actually hold by the DTH.

For example, is a DTH has this assigned array:

```
[{
    fromProposalId: 1,
    votes: 1e16
},{
    fromProposalId: 4,
    votes: 3e16
}]
```

means that for proposals 1,2,3 h has 1 token of voting power. And from proposal 4 to the last he has 3 tokens of voting power. 

So, at the beginning of the DAO, all  DTH has an array with one element where fromProposalId = 1 and votes are the current number of tokens that the DTH Owns.

```
function getTokenHolderVotingRights(address _tokenHolder, uint _proposalID) constant returns (uint votes) {
        VotesAssignedToTokenHolder[] assignements = votesAssignedToTokenHolders[_tokenHolder];
        if (assignements.length == 0) {
            return 0;
        }

        uint i;

        for (i = assignements.length; i>0; i-- ) {
            VotesAssignedToTokenHolder a = assignements[i-1];
            if (_proposalID >= a.fromProposalId) return a.votes;
        }

        return 0;
}

function transferTokenHolderVotes(address _from, address _to, uint _value) internal constant returns(bool) {

       if (_value == 0) {
           return true;
       }

      // Remove _from votes
       var previousVotesFrom = getTokenHolderVotingRights(_from, proposals.length);
       if (previousVotesFrom < _value) {
           throw;
       }
       updateTokenHolderVotes(_from, previousVotesFrom - _value);

       var previousVotesTo = getTokenHolderVotingRights(_to, proposals.length);
       updateTokenHolderVotes(_to, previousVotesTo + _value);

       return true;
}

function updateTokenHolderVotes(address _tokenHolder, uint _votes) internal returns (bool) {
       VotesAssignedToTokenHolder[] assignments = votesAssignedToTokenHolders[_tokenHolder];

       if ((assignments.length == 0) || (assignments[assignments.length -1].fromProposalId < proposals.length)) {
           VotesAssignedToTokenHolder newAssignment = assignments[ assignments.length++ ];
           newAssignment.fromProposalId = proposals.length;
           newAssignment.votes = _votes;
       } else {
           VotesAssignedToTokenHolder oldAssignment = assignments[assignments.length-1];
           oldAssignment.votes = _votes;
       }

       return true;
}
```

`transferTokenHolderVotes` is called on the transfer functions to transfer the voting rights.

`getTokenHolderVotingRights` is a constant function that returns the number of votes that a DTH had/have for a given proposal. This number will always be fixed for the submitted proposals.

**Comment by area** [comment]
If I transfer tokens back and forth between two users, causing their arrays in `votesAssignedToTokenHolders` to grow, what prevents the loop in `getTokenHolderVotingRights` using an arbitrarily large amount of gas, rendering those accounts unable to transfer tokens or vote once the gas required exceeds the block limit?

**Comment by jbaylina** [comment]
@area A new element in the array is generated ONLY when a new proposal is made. If no new proposals are made between transfers, then no new items in the array are inserted, only the last items of the array in the `from` and `to` accounts are updated.
The problem with this might came with the "split" proposals. I believe that if the "Withdraw" function is implemented then this will no be a problem any more.
Another limit might be the total number of concurrent proposals. If we don't count solo split proposals, then this number should be controlled. See DIR 7 for controlling this number.

**Comment by area** [comment]
Okay, so it takes longer for the problem to manifest itself, but it still ends up being a problem over a long enough timescale, surely?

**Comment by jbaylina** [comment]
It might be a problem  if the number of regular proposals increases in the order of hundreds. And in the while we expect that the gas limit increase, specially with the PoS arrival.  
But even in that situation of high number of proposals, this problem only will happen if you make a transfer with the same account in the middle of each proposal. You will be harming yourself.
If this DIR is implemented, it may be  good to do some tests to evaluate which are those limits, but If the proposal submission is a regulated, I don't really see this problem a real issue.

**Comment by CJentzsch** [comment]
solved through "unvoting"
