### ISSUE TITLE
'proposal' test failed

### ISSUE THREAD

**Issue by AnthonyAkentiev** [slockit/DAO#271]
Hi guys. I'm having problem running tests.
I am in develop branch (latest commit) and working on a MacOS 10.11.5 El Capitan.

``` bash
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.3.5-371690f0/Release-Darwin/appleclang/JIT

$ geth --version
VERSION:
   1.4.8-stable-98be7cd8

$ python --version
Python 2.7.10
```
### How to reproduce

1) I go to _tests_ folder
2) I run proposal test like this:

``` bash
python test.py --verbose --deploy-creation-seconds 120 --scenario proposal --clean-chain
```

I need to set --deploy-creation-seconds because of timing issues on my machine. 
### The output of this test is:

``` bash
Cleaning blockchain data directory ...
Creating accounts and genesis block ...
Running 'accounts.js' script
I0706 17:28:54.631281 ethdb/database.go:82] Alloted 16MB cache and 16 file handles to data/chaindata
I0706 17:28:54.752031 cmd/geth/main.go:305] successfully wrote genesis block and/or chain rule set: e58cb5ec9ca7e3f514cc0b70432cb8190202ee625e00b197a6c2f46032c5727b
Done!
Checking out 'v1.0' DAO contracts ...
Compiling the DAO contracts...
    Compiling /Users/tonykent/ChainCloud/DAO-1.0/USNRewardPayOutCopy.sol...
Creating deploy_dao_creator.js
Running 'deploy_dao_creator.js' script
dao_creator_address is: 0x03755d992f307f910e8513358a89ca7225511377
Creating deploy_dao.js
Running 'deploy_dao.js' script
dao_address is: 0xfc1f69344398780ed726732f0984e65944650b10
Creating deploy_offer.js
Running 'deploy_offer.js' script
offer_address is: 0xcc9b9c6d84a83bf2df1a6a0d74677dd8bd6e5742
Creating deploy_usn.js
Running 'deploy_usn.js' script
usn_address is: 0xff9787cbd032ab75ec1f47cf32586743b996cd89
Creating fuel.js
Notice: Fueling period is 80 seconds so the test will wait as much
Running 'fuel.js' script
Tests for scenario 'fuel' PASSED!
Creating proposal.js
Notice: Debate period is 20 seconds so the test will wait as much
Running 'proposal.js' script
ERROR: Could not parse 'proposal' output properly.
Output was:
unlocking accounts
Add offer contract as allowed recipient
'creator_balance_before' = 1.33699999999999959998303317587531748e+35
Creating a new proposal to: 'Test Proposal'
Proposal succesfully created
'creator_balance_after_proposal' = 1.33699999999999934993351977587531748e+35
'calculated_deposit' = 25.00495134
'dao_proposals_number' = 1
Deadline is: 1467815539 Voting ... 
User 0 is voting [true]. His token balance is: 15 ether and NOW is: 1467815521
User 1 is voting [true]. His token balance is: 40 ether and NOW is: 1467815521
User 2 is voting [true]. His token balance is: 20 ether and NOW is: 1467815521
User 3 is voting [false]. His token balance is: 29 ether and NOW is: 1467815521
User 4 is voting [false]. His token balance is: 7 ether and NOW is: 1467815522
'proposal_yay' = 75
'proposal_nay' = 36
'contractor_balance_before' = 1.33699999999999979975413621704280331e+35
Wait for end of debating period
After debating period. NOW is: 1467815546
Attempting to execute proposal for: 'Test Proposal'.
Expected the proposal to be closed but it's not
Expected the proposal for: 'Test Proposal to pass.
TEST FAIL: Failed to execute proposal for: 'Test Proposal'.
js error:   [function() {
    miner.stop();
    console.log("After debating period. NOW is: " + Math.floor(Date.now() / 1000));
    attempt_execute_proposal(
        dao, // target DAO
        prop_id, // proposal ID
        '0x2ca15122', // transaction bytecode
        proposalCreator, // proposal creator
        true, // should the proposal be closed after this call?
        true // should the proposal pass?
    );

    addToTest('creator_balance_after_execution', eth.getBalance(proposalCreator));
    addToTest('contractor_balance_after', eth.getBalance(contractor));

    addToTest(
        'onetime_costs',
        web3.fromWei(testMap['contractor_balance_after'].sub(testMap['contractor_balance_before']))
    );
    addToTest(
        'deposit_returned',
        testMap['creator_balance_after_execution'].sub(testMap['creator_balance_before']).lt(new BigNumber(100000000000000000))
    );
    addToTest('offer_promise_valid', offer.getIsContractValid());

    testResults();
}]
```
### These tests are OK:
- deploy
- fuel
- deposit
- singlesplit

But almost every other test fails because of the 'proposal'...
### Please HELP!

I contacted Lefteris Karapetsas but unfortunately he has no time to look/fix that. I really need tests to be ok, because i am developing my own DAO currently.

Maybe someone could help me? Thanks in advance.

**Comment by LefterisJP** [comment]
Hello Anthony,

As I already told you in the email we were in the process of updating the tests when this whole DAO hack mess happened. Last time I did run the tests everything was fine but since the upgrading of the tests was left in the middle it is quite possible some things are off.

If I find some time I will try to help you but please do understand that this is not a priority right now and that we are seriously undermanned.

Regarding the upgrades we wanted to do to the tests:
1. Needed to fake PoW totally
2. Fake timestamps in blocks and make time pass as fast as you want.

This all would have been possible with the inclusion of `eth --test` instead of geth, essentially an amazing testing framework being developed by the C++ client team and included in latest versions of the C++ client.

I would strongly advise you to wait before developing any DAO based on this code at the moment. Wait until the dust settles, the code is fixed and vetted/audited.

**Comment by AnthonyAkentiev** [comment]
Thank you for support. 
Of course i will wait for new code and new tests. 

But i thought that tests in ‘old’ code (that was deployed as The DAO at 0xbb9bc244d798123fde783fcc1c72d3bb8c189413)
are OK. Unfortunately they are not, at least on my machine.
 
Right now i am using that old code as a code-base for my own DAO and couple of tests there work as expected. I wish that one day your team will release new tests and i will just merge that into my branch!

I really appreciate that you have found some time for me. I understand how scarce the time is for you.
