### ISSUE TITLE
The DAO whitepaper

### ISSUE THREAD

**Issue by khannea** [slockit/DAO#286]
Hello,
I am desperately searching The DAO WhitePaper. I really want to know how it worked.
Do you know where I could find thoses documentation? I can't find it anywhere....

Because the site https://download.slock.it/public/DAO/WhitePaper.pdf is no longer working.

Thank you for your response

**Comment by MartinDelille** [comment]
Available here: https://web.archive.org/web/20180414020006/https://download.slock.it/public/DAO/WhitePaper.pdf

**Comment by khannea** [comment]
Thank you A LOT!
