### ISSUE TITLE
Test: scenario deploy fails "TestContext instance has no attribute accounts"

### ISSUE THREAD

**Issue by colm** [slockit/DAO#53]
python test.py --scenario deploy
Compiling the DAO contracts...
    Compiling /home/__/DAO/DAOcopy.sol...
    Compiling /home__/DAO/SampleOffer.sol...
Creating deploy.js
Traceback (most recent call last):
  File "test.py", line 265, in <module>
    ctx.run_test(args)
  File "test.py", line 256, in run_test
    self.run_scenario(self.args.scenario)
  File "test.py", line 246, in run_scenario
    scenario.run(self)
  File "/home/__/DAO/tests/scenarios/deploy/run.py", line 30, in run
    cb_before_creation=calculate_closing_time
  File "test.py", line 212, in create_js_file
    write_js("{}.js".format(name), s, len(self.accounts))
AttributeError: TestContext instance has no attribute 'accounts'

**Comment by LefterisJP** [comment]
Hello, I was always testing using the `--clean-blockchain` argument so I never noticed how accounts were not created without it. I just fixed it in a commit.

But take note: 
You will need a latest develop geth in order for the tests to work properly. You can specify the `geth` and the `solc` executable by `--geth` and `--solc` respectively.

**Comment by colm** [comment]
Cool thanks, I'll keep playing :dancer:
