### ISSUE TITLE
Setting deploy-sale-seconds typed as string

### ISSUE THREAD

**Issue by colm** [slockit/DAO#54]
```
python test.py --solc /usr/bin/solc --geth /usr/bin/geth --clean-chain --deploy-sale-seconds 10 --scenario deploy
Cleaning blockchain data directory ...
Creating accounts and genesis block ...
Done!
Compiling the DAO contracts...
    Compiling /home/__/slock.it/DAO/DAOcopy.sol...
    Compiling /home/__/slock.it/DAO/SampleOffer.sol...
Creating deploy.js
Traceback (most recent call last):
  File "test.py", line 266, in <module>
    ctx.run_test(args)
  File "test.py", line 257, in run_test
    self.run_scenario(self.args.scenario)
  File "test.py", line 247, in run_scenario
    scenario.run(self)
  File "/home/__/DAO/tests/scenarios/deploy/run.py", line 30, in run
    cb_before_creation=calculate_closing_time
  File "test.py", line 211, in create_js_file
    substitutions = cb_before_creation(self, name, substitutions)
  File "/home/__/DAO/tests/scenarios/deploy/run.py", line 13, in calculate_closing_time
    obj.closing_time = seconds_in_future(obj.args.deploy_sale_seconds)
  File "/home/__/DAO/tests/utils.py", line 64, in seconds_in_future
    return ts_now() + secs
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```
I have a fix will submit pull request.

**Comment by LefterisJP** [comment]
Thanks for noticing. At some point I moved all scenario arguments to json files so the python types may not be properly converted if default is not used anymore. I can fix now, but if you want to make a PR why not, go ahead.

One note: The framework looks under `/usr/bin/` for `solc` and for `geth` so no need to specify them if you have them there.

**Comment by colm** [comment]
Its probably better for you to do it because I am doing a messy fix 

in utils.py 

```
def seconds_in_future(secs):
    return ts_now() + float(secs)
```

its probably better to fix it at the source of the problem.

**Comment by LefterisJP** [comment]
okay I will handle it, but still thanks for noticing! I create the scenarios, make the arguments, give sensible default values which are the ones I want to test with and don't experiment too much with them ;)

**Comment by colm** [comment]
No problem. I am having fun playing with the tests. I wrote some tests for the DAO and its a grate learning experience seeing how another person does the same thing. :baby_chick:
