### ISSUE TITLE
SampleOffer.sol marginally inefficent code

### ISSUE THREAD

**Issue by colm** [slockit/DAO#55]
msg.sender != address(client) already prevented by callingRestriction modifier so should not be called a second time in the if statement. 

```
function setRewardDivisor(uint _rewardDivisor) callingRestriction {
        if (_rewardDivisor < 50 && msg.sender != address(client))
            throw; // 2% is the default max reward
        rewardDivisor = _rewardDivisor;
    }
```

**Comment by LefterisJP** [comment]
I believe you are correct. Let's have @CJentzsch also have a look at it

**Comment by colm** [comment]
Ignore those references. I created a pull request resolving this issue and another similar.  
https://github.com/slockit/DAO/pull/56
