### ISSUE TITLE
Stalker Attack

### ISSUE THREAD

**Issue by colm** [slockit/DAO#57]
Okay lets say you and me are in the DAO together. I own 51 tokens and you own 49. I stop you from doing anything so you vote to change service provider. I vote with you and we are still in the same position. I follow you to the new DAO. 

So lets say you split your tokens and take 1 token of them and create a new service provider. Then I take 1.01 of my tokens and agree with you to switch service providers with you, following you. Then you are in the same position unable to withdraw your ETH. That leaves me owning 49.99 and you with 48 in the original DAO and me with 1.01 and you with 1 in the new DAO. 

So we continue this you trying to run away and me following you until we have split the DAO to its ultimate granularity which is 1 WEI each (if i am not mistaken). But at this stage fees will have eaten all our ETH. But some people will make a deal with me to get their ETH in exchange for theirs. 

At any time I can split the DAO and withdraw my ETH. Letting people have theirs back. But only after made some profit.

**Comment by LefterisJP** [comment]
As discussed in the DAO channel with you this is a non-issue due to: https://github.com/slockit/DAO/blob/master/DAO.sol#L528

**Comment by colm** [comment]
Having thought about this a little more I am not so sure if `!p.votedYes[msg.sender]` really prevents this. If a 51% attacker sets the proposal deposit to 10,000,000 ETH. Then no proposals are possible except new service providers. In this case if the attacker agrees to all proposals then they will be able to STALK escaping users to their new DAOS. 

The condition `blocked[msg.sender] != _proposalID)` seems to mitigate this. By ensuring a user can only vote on one split and one only. But an attacker can simply split their % of the tokens into fragments which are equal to 51% of each user and then mirror that users actions from these accounts. 

This will effectively sequester a users ETH. Opening the possibility of holding them to ransom.
