### ISSUE TITLE
 DAO splits in parallel may be broken.

### ISSUE THREAD

**Issue by colm** [slockit/DAO#59]
There may be a problem on https://github.com/slockit/DAO/blob/master/DAO.sol#L545If two groups are splitting into two separate DAO's the one that calls splitDAO function first will end up with less ETH in their DAO at the end. Due to  p.splitData[0].totalSupply = totalSupply; being set at the time it is first called and not updated as tokens are burnt.
`
        uint fundsToBeMoved =
            (balances[msg.sender] * p.splitData[0].splitBalance) /
            p.splitData[0].totalSupply;
        if (p.splitData[0].newDAO.buyTokenProxy.value(fundsToBeMoved)(msg.sender) == false)
            throw;`

https://github.com/slockit/DAO/blob/master/DAO.sol#L552

Say the DAO has 100 DAO and 100 eth. And it splits into 2 DAO's
GROUP 1:
Calls splitDAO at the start so its totalSupply=100. Then all its the person withdraws their ETH in one go. rewardTokenToBeMoved = 50 x 50/100  = 25
GROUP 2:
DAO2 calls split DAO at after all this has happened totalSupply=50. Then the person withdraws their ETH in one go.  rewardTokenToBeMoved = 50 x 50/50 = 50.
Something is not quite right in the number here. total should be 100. But it might help to illustrate what I am getting at. DAO splits in parallel may be broken.

**Comment by CJentzsch** [comment]
Actually not. *But* the second split is of course of the remainder. So lets say 50% split of from the first DAO. Then the second split can only split of from the remainder. But it just works fine. Your numbers ther don't really make sense to me. If you are not convinced yet, try to give me a very very concrete example of an unfair situation.
