### ISSUE TITLE
proposalDeposit should be set initatlly to 0

### ISSUE THREAD

**Issue by colm** [slockit/DAO#60]
It is currently 20. This is a problem because in a few years ETH may be worth 1000 USD and in the case where someone wants to withdraw their ETH they will split the DAO and the proposal to withdraw money will require 20*1000 = 20,000 USD. Most people do not have this ETH available and will thus not be able to withdraw it.

**Comment by colm** [comment]
https://github.com/slockit/DAO/pull/61

**Comment by CJentzsch** [comment]
(see comment to the PR)
