### ISSUE TITLE
SplitDAO_fundsToBeMoved: Using proposal deposit to increase this.balance, increaseing fundsToBeMoved

### ISSUE THREAD

**Issue by colm** [slockit/DAO#65]
1.  I create a proposal with a huge deposit say 1000 ETH
2.  I split the DAO Which this sets `p.splitData[0].splitBalance = this.balance` effectively. this.balance includes my 1000 ETH

`fundsToBeMoved = (balances[msg.sender] * p.splitData[0].splitBalance) / p.splitData[0].totalSupply;`

4. I get 1000 times my original ETH.
5. My proposal meets the quorum and i get my ETH deposit back

Is this where proposal deposits are stored?

**Comment by CJentzsch** [comment]
you forgot the last part of the equation: `p.splitData[0].splitBalance = this.balance - p.proposalDeposit;`
https://github.com/slockit/DAO/blob/master/DAO.sol#L550

The proposal deposit is not counted in the split balance.

**Comment by colm** [comment]
But `p.proposalDeposit`only contains the proposal deposit for this proposal. If I include the high proposal deposit in another proposal this will not be subtracted out here. Is that correct?

**Comment by CJentzsch** [comment]
correct

**Comment by colm** [comment]
Then this is a bug. I can send a proposal with a huge_deposit. Then create a seperate proposal to Split the DAO get myshares*eth_balance + myshares*huge_deposit. Then when the proposal meets the quoram I get my huge_deposit back.
