### ISSUE TITLE
Permanently blocked tokens due to malforumed hash

### ISSUE THREAD

**Issue by colm** [slockit/DAO#75]
If someone votes on a proposal that has a malformed hash. [Then](https://github.com/slockit/DAO/blob/master/DAO.sol#L488) 

`if ... ... ... 
           || p.proposalHash != sha3(p.recipient, p.amount, _transactionData)) {
            throw;
        }` 

will cause their tokens to be blocked forever. Preventing them from splitting or transferring.

**Comment by LefterisJP** [comment]
@colm As we also discussed in the chat, voting in a proposal that is either malformed or is made as trap is dangerous. As you mentioned someone could set an almost infinite `votingDeadline` and whoever votes in the proposal will be locked forever. It's not a logic bug and all users should use due diligence and thoroughly check the contents of each proposal they vote for at the moment.

Nonetheless a mistaken proposal index or a bug in the UI leading to calling `vote()` with the trap proposal ID would be fatal for the token holder. We have to evaluate if it is worth giving a vote/proposal canceling functionality or not.

@CJentzsch thoughts?

**Comment by CJentzsch** [comment]
Here is a max debating period: https://github.com/slockit/DAO/pull/85
The hash is neccessary to check the transactionbyteCode.
