### ISSUE TITLE
proposals.lenght incramented twice to prevent proposalID = 0, should only be incramented once. 

### ISSUE THREAD

**Issue by colm** [slockit/DAO#76]
I don't think you need to increment `proposals.lenght` [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L350) as its already done [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L406)

**Comment by LefterisJP** [comment]
I am not sure I follow. [In the constructor](https://github.com/slockit/DAO/blob/master/DAO.sol#L350) it's incremented once (could as well be set to 1, and may actually be a better choice for readability).

Then inside [newProposal()](https://github.com/slockit/DAO/blob/master/DAO.sol#L406) it is incremented each time a new proposal is made.

**Comment by LefterisJP** [comment]
@colm Do you agree with my assesment? Or is there anything additional you suspect could be off here?

**Comment by CJentzsch** [comment]
@colm Lefteris is correct here. Its increased by one on the beginning, and then only when a new proposal is added.
