### ISSUE TITLE
Prventing splits by `executeProposal` and then unblocking users `isBlocked`

### ISSUE THREAD

**Issue by colm** [slockit/DAO#81]
Someone can execute a proposal being used to [split the DAO](https://github.com/slockit/DAO/blob/master/DAO.sol#L551) 

That will close the proposal [here](https://github.com/slockit/DAO/blob/master/DAO.sol#L493) then if an attacker calls `isBlocked` using the spitting user address their `isBlocked` Id will be set to 0 because the proposal is closed. Then [`blocked[msg.sender] != _proposalID`](https://github.com/slockit/DAO/blob/master/DAO.sol#L551) will prevent this user from splitting.

**Comment by CJentzsch** [comment]
fix https://github.com/slockit/DAO/pull/84
